---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: download prometheus node installer
    action: shell wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-armv7.tar.gz
  
  - name: unzip file
    action: shell tar xvf node_exporter-1.3.1.linux-armv7.tar.gz

  - name: start node exporter
    action: sudo ./node_exporter-1.3.1.linux-armv7/node_exporter