---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: download prometheus node installer
    action: shell wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
  
  - name: unzip file
    action: shell tar xvf node_exporter-1.3.1.linux-amd64.tar.gz

  - name: cd to directory
    action: shell cd node_exporter-1.3.1.linux-amd64

  - name: create dir to test
    action: shell mkdir testdirectory

  - name: copy node_exporter
    action: shell cp node_exporter /usr/local/bin