---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install prometheus node
    action: shell wget wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    action: shell tar xvf node_exporter-1.3.1.linux-amd64.tar.gz
    action: shell cd node_exporter-1.3.1.linux-amd64
    action: shell cp node_exporter /usr/local/bin